#!/bin/bash
#SPDX-License-Identifier: Apache-2.0
#Copyright 2018-2025 Gliim LLC. 
#Licensed under Apache License v2. See LICENSE file.
#On the web http://rimstone-lang.com/ - this file is part of RimStone framework.


# Set variables for building and installing a RimStone application. 
# If your system doesn't conform, you can change these variables to fit

function lowest_version() { 
    echo "$@" | sed 's/ /\n/g'| sort -V | head -n 1 
}

#utility to check for versions matching
if [ "$1" == "greater_than_eq" ]; then
    L=$(lowest_version "$2" "$3" )
    if [ "$L" == "$3" ]; then echo "1"; else echo "0"; fi
    exit 0
fi

#do not do all twice if already done
if [ "$RIM_SYSTEM_DONE" != "1" ]; then

#determine operating system, some don't have /etc/os-release (or it isn't linked), try the alternative
    if [ -f "/etc/os-release" ]; then
        . /etc/os-release
    elif [ -f "/usr/lib/os-release" ]; then
        . /usr/lib/os-release
    elif [ -f "/etc/lsb-release" ]; then
#check if lsb-release present, and use it to override os-release, as it is generally more accurate
        . /etc/lsb-release
    else
        ID="unknown"
        VERSION_ID="unknown"
    fi
    export RIM_PLATFORM_ID="$ID"
    export RIM_PLATFORM_VERSION="$VERSION_ID"


#the following three should not be changed manually, make tools set them
    export RIM_LIBRARY_PATH=$HOME/.rimstone/lib
    export RIM_INCLUDE_PATH=$HOME/.rimstone/include
    export RIM_BIN_PATH=$HOME/.rimstone/bin
    export RIM_VERSION=100.100

#do not execute again if already done
    export RIM_SYSTEM_DONE=1
fi 


#
#
#
#From here on, only system requests are allowed, each exiting with 'exit'
#
#
#

if [ "$1" == "pgconf" ]; then
    ECODE="0"
    which pg_config 2>/dev/null 1>/dev/null || ECODE=$?
    if [ "$ECODE" == "0" ]; then
        echo "yes"
    else
        echo "no"
    fi
    exit 0
fi

if [ "$1" == "showid" ]; then
    echo $RIM_PLATFORM_ID
    exit 0
fi




